/**
 * Created by USER on 02/03/2018.
 */
const magentoSchema = [
  {
    fields: [],
    table: 'admin_passwords',
    destination_table_name: 'admin_passwords',
    primary_key: 'password_id',
  },
  {
    fields: [],
    table: 'admin_system_messages',
    destination_table_name: 'admin_system_messages',
    primary_key: 'identity',
  },
  {
    fields: [],
    table: 'admin_user',
    destination_table_name: 'admin_user',
    primary_key: 'user_id',
  },
  {
    fields: [],
    table: 'admin_user_session',
    destination_table_name: 'admin_user_session',
    primary_key: 'id',
  },
  {
    fields: [],
    table: 'adminnotification_inbox',
    destination_table_name: 'adminnotification_inbox',
    primary_key: 'notification_id',
  },
  {
    fields: [],
    table: 'authorization_role',
    destination_table_name: 'authorization_role',
    primary_key: 'role_id',
  },
  {
    fields: [],
    table: 'authorization_rule',
    destination_table_name: 'authorization_rule',
    primary_key: 'rule_id',
  },
  {
    fields: [],
    table: 'cache',
    destination_table_name: 'cache',
    primary_key: 'id',
  },
  {
    fields: [],
    table: 'cache_tag',
    destination_table_name: 'cache_tag',
    primary_key: 'tag',
  },
  {
    fields: [],
    table: 'captcha_log',
    destination_table_name: 'captcha_log',
    primary_key: 'type',
  },
  {
    fields: [],
    table: 'catalog_category_entity',
    destination_table_name: 'catalog_category_entity',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_category_entity_datetime',
    destination_table_name: 'catalog_category_entity_datetime',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'catalog_category_entity_decimal',
    destination_table_name: 'catalog_category_entity_decimal',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'catalog_category_entity_int',
    destination_table_name: 'catalog_category_entity_int',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'catalog_category_entity_text',
    destination_table_name: 'catalog_category_entity_text',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'catalog_category_entity_varchar',
    destination_table_name: 'catalog_category_entity_varchar',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'catalog_category_product',
    destination_table_name: 'catalog_category_product',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_category_product_index',
    destination_table_name: 'catalog_category_product_index',
    primary_key: 'category_id',
  },
  {
    fields: [],
    table: 'catalog_category_product_index_tmp',
    destination_table_name: 'catalog_category_product_index_tmp',
    primary_key: null,
  },
  {
    fields: [],
    table: 'catalog_compare_item',
    destination_table_name: 'catalog_compare_item',
    primary_key: 'catalog_compare_item_id',
  },
  {
    fields: [],
    table: 'catalog_eav_attribute',
    destination_table_name: 'catalog_eav_attribute',
    primary_key: 'attribute_id',
  },
  {
    fields: [],
    table: 'catalog_product_bundle_option',
    destination_table_name: 'catalog_product_bundle_option',
    primary_key: 'option_id',
  },
  {
    fields: [],
    table: 'catalog_product_bundle_option_value',
    destination_table_name: 'catalog_product_bundle_option_value',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'catalog_product_bundle_price_index',
    destination_table_name: 'catalog_product_bundle_price_index',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_bundle_selection',
    destination_table_name: 'catalog_product_bundle_selection',
    primary_key: 'selection_id',
  },
  {
    fields: [],
    table: 'catalog_product_bundle_selection_price',
    destination_table_name: 'catalog_product_bundle_selection_price',
    primary_key: 'selection_id',
  },
  {
    fields: [],
    table: 'catalog_product_bundle_stock_index',
    destination_table_name: 'catalog_product_bundle_stock_index',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_entity',
    destination_table_name: 'catalog_product_entity',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_entity_datetime',
    destination_table_name: 'catalog_product_entity_datetime',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'catalog_product_entity_decimal',
    destination_table_name: 'catalog_product_entity_decimal',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'catalog_product_entity_gallery',
    destination_table_name: 'catalog_product_entity_gallery',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'catalog_product_entity_int',
    destination_table_name: 'catalog_product_entity_int',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'catalog_product_entity_media_gallery',
    destination_table_name: 'catalog_product_entity_media_gallery',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'catalog_product_entity_media_gallery_value',
    destination_table_name: 'catalog_product_entity_media_gallery_value',
    primary_key: 'record_id',
  },
  {
    fields: [],
    table: 'catalog_product_entity_media_gallery_value_to_entity',
    destination_table_name: 'catalog_product_entity_media_gallery_value_to_entity',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'catalog_product_entity_media_gallery_value_video',
    destination_table_name: 'catalog_product_entity_media_gallery_value_video',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'catalog_product_entity_text',
    destination_table_name: 'catalog_product_entity_text',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'catalog_product_entity_tier_price',
    destination_table_name: 'catalog_product_entity_tier_price',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'catalog_product_entity_varchar',
    destination_table_name: 'catalog_product_entity_varchar',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_eav',
    destination_table_name: 'catalog_product_index_eav',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_eav_decimal',
    destination_table_name: 'catalog_product_index_eav_decimal',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_eav_decimal_idx',
    destination_table_name: 'catalog_product_index_eav_decimal_idx',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_eav_decimal_tmp',
    destination_table_name: 'catalog_product_index_eav_decimal_tmp',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_eav_idx',
    destination_table_name: 'catalog_product_index_eav_idx',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_eav_tmp',
    destination_table_name: 'catalog_product_index_eav_tmp',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_price',
    destination_table_name: 'catalog_product_index_price',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_price_bundle_idx',
    destination_table_name: 'catalog_product_index_price_bundle_idx',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_price_bundle_opt_idx',
    destination_table_name: 'catalog_product_index_price_bundle_opt_idx',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_price_bundle_opt_tmp',
    destination_table_name: 'catalog_product_index_price_bundle_opt_tmp',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_price_bundle_sel_idx',
    destination_table_name: 'catalog_product_index_price_bundle_sel_idx',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_price_bundle_sel_tmp',
    destination_table_name: 'catalog_product_index_price_bundle_sel_tmp',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_price_bundle_tmp',
    destination_table_name: 'catalog_product_index_price_bundle_tmp',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_price_cfg_opt_agr_idx',
    destination_table_name: 'catalog_product_index_price_cfg_opt_agr_idx',
    primary_key: 'parent_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_price_cfg_opt_agr_tmp',
    destination_table_name: 'catalog_product_index_price_cfg_opt_agr_tmp',
    primary_key: 'parent_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_price_cfg_opt_idx',
    destination_table_name: 'catalog_product_index_price_cfg_opt_idx',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_price_cfg_opt_tmp',
    destination_table_name: 'catalog_product_index_price_cfg_opt_tmp',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_price_downlod_idx',
    destination_table_name: 'catalog_product_index_price_downlod_idx',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_price_downlod_tmp',
    destination_table_name: 'catalog_product_index_price_downlod_tmp',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_price_final_idx',
    destination_table_name: 'catalog_product_index_price_final_idx',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_price_final_tmp',
    destination_table_name: 'catalog_product_index_price_final_tmp',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_price_idx',
    destination_table_name: 'catalog_product_index_price_idx',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_price_opt_agr_idx',
    destination_table_name: 'catalog_product_index_price_opt_agr_idx',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_price_opt_agr_tmp',
    destination_table_name: 'catalog_product_index_price_opt_agr_tmp',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_price_opt_idx',
    destination_table_name: 'catalog_product_index_price_opt_idx',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_price_opt_tmp',
    destination_table_name: 'catalog_product_index_price_opt_tmp',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_price_tmp',
    destination_table_name: 'catalog_product_index_price_tmp',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_tier_price',
    destination_table_name: 'catalog_product_index_tier_price',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'catalog_product_index_website',
    destination_table_name: 'catalog_product_index_website',
    primary_key: 'website_id',
  },
  {
    fields: [],
    table: 'catalog_product_link',
    destination_table_name: 'catalog_product_link',
    primary_key: 'link_id',
  },
  {
    fields: [],
    table: 'catalog_product_link_attribute',
    destination_table_name: 'catalog_product_link_attribute',
    primary_key: 'product_link_attribute_id',
  },
  {
    fields: [],
    table: 'catalog_product_link_attribute_decimal',
    destination_table_name: 'catalog_product_link_attribute_decimal',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'catalog_product_link_attribute_int',
    destination_table_name: 'catalog_product_link_attribute_int',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'catalog_product_link_attribute_varchar',
    destination_table_name: 'catalog_product_link_attribute_varchar',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'catalog_product_link_type',
    destination_table_name: 'catalog_product_link_type',
    primary_key: 'link_type_id',
  },
  {
    fields: [],
    table: 'catalog_product_option',
    destination_table_name: 'catalog_product_option',
    primary_key: 'option_id',
  },
  {
    fields: [],
    table: 'catalog_product_option_price',
    destination_table_name: 'catalog_product_option_price',
    primary_key: 'option_price_id',
  },
  {
    fields: [],
    table: 'catalog_product_option_title',
    destination_table_name: 'catalog_product_option_title',
    primary_key: 'option_title_id',
  },
  {
    fields: [],
    table: 'catalog_product_option_type_price',
    destination_table_name: 'catalog_product_option_type_price',
    primary_key: 'option_type_price_id',
  },
  {
    fields: [],
    table: 'catalog_product_option_type_title',
    destination_table_name: 'catalog_product_option_type_title',
    primary_key: 'option_type_title_id',
  },
  {
    fields: [],
    table: 'catalog_product_option_type_value',
    destination_table_name: 'catalog_product_option_type_value',
    primary_key: 'option_type_id',
  },
  {
    fields: [],
    table: 'catalog_product_relation',
    destination_table_name: 'catalog_product_relation',
    primary_key: 'parent_id',
  },
  {
    fields: [],
    table: 'catalog_product_super_attribute',
    destination_table_name: 'catalog_product_super_attribute',
    primary_key: 'product_super_attribute_id',
  },
  {
    fields: [],
    table: 'catalog_product_super_attribute_label',
    destination_table_name: 'catalog_product_super_attribute_label',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'catalog_product_super_link',
    destination_table_name: 'catalog_product_super_link',
    primary_key: 'link_id',
  },
  {
    fields: [],
    table: 'catalog_product_website',
    destination_table_name: 'catalog_product_website',
    primary_key: 'product_id',
  },
  {
    fields: [],
    table: 'catalog_url_rewrite_product_category',
    destination_table_name: 'catalog_url_rewrite_product_category',
    primary_key: null,
  },
  {
    fields: [],
    table: 'cataloginventory_stock',
    destination_table_name: 'cataloginventory_stock',
    primary_key: 'stock_id',
  },
  {
    fields: [],
    table: 'cataloginventory_stock_item',
    destination_table_name: 'cataloginventory_stock_item',
    primary_key: 'item_id',
  },
  {
    fields: [],
    table: 'cataloginventory_stock_status',
    destination_table_name: 'cataloginventory_stock_status',
    primary_key: 'product_id',
  },
  {
    fields: [],
    table: 'cataloginventory_stock_status_idx',
    destination_table_name: 'cataloginventory_stock_status_idx',
    primary_key: 'product_id',
  },
  {
    fields: [],
    table: 'cataloginventory_stock_status_tmp',
    destination_table_name: 'cataloginventory_stock_status_tmp',
    primary_key: 'product_id',
  },
  {
    fields: [],
    table: 'catalogrule',
    destination_table_name: 'catalogrule',
    primary_key: 'rule_id',
  },
  {
    fields: [],
    table: 'catalogrule_customer_group',
    destination_table_name: 'catalogrule_customer_group',
    primary_key: 'rule_id',
  },
  {
    fields: [],
    table: 'catalogrule_group_website',
    destination_table_name: 'catalogrule_group_website',
    primary_key: 'rule_id',
  },
  {
    fields: [],
    table: 'catalogrule_product',
    destination_table_name: 'catalogrule_product',
    primary_key: 'rule_product_id',
  },
  {
    fields: [],
    table: 'catalogrule_product_price',
    destination_table_name: 'catalogrule_product_price',
    primary_key: 'rule_product_price_id',
  },
  {
    fields: [],
    table: 'catalogrule_website',
    destination_table_name: 'catalogrule_website',
    primary_key: 'rule_id',
  },
  {
    fields: [],
    table: 'catalogsearch_fulltext_scope1',
    destination_table_name: 'catalogsearch_fulltext_scope1',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'checkout_agreement',
    destination_table_name: 'checkout_agreement',
    primary_key: 'agreement_id',
  },
  {
    fields: [],
    table: 'checkout_agreement_store',
    destination_table_name: 'checkout_agreement_store',
    primary_key: 'agreement_id',
  },
  {
    fields: [],
    table: 'cms_block',
    destination_table_name: 'cms_block',
    primary_key: 'block_id',
  },
  {
    fields: [],
    table: 'cms_block_store',
    destination_table_name: 'cms_block_store',
    primary_key: 'block_id',
  },
  {
    fields: [],
    table: 'cms_page',
    destination_table_name: 'cms_page',
    primary_key: 'page_id',
  },
  {
    fields: [],
    table: 'cms_page_store',
    destination_table_name: 'cms_page_store',
    primary_key: 'page_id',
  },
  {
    fields: [],
    table: 'core_config_data',
    destination_table_name: 'core_config_data',
    primary_key: 'config_id',
  },
  {
    fields: [],
    table: 'cron_schedule',
    destination_table_name: 'cron_schedule',
    primary_key: 'schedule_id',
  },
  {
    fields: [],
    table: 'customer_address_entity',
    destination_table_name: 'customer_address_entity',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'customer_address_entity_datetime',
    destination_table_name: 'customer_address_entity_datetime',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'customer_address_entity_decimal',
    destination_table_name: 'customer_address_entity_decimal',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'customer_address_entity_int',
    destination_table_name: 'customer_address_entity_int',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'customer_address_entity_text',
    destination_table_name: 'customer_address_entity_text',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'customer_address_entity_varchar',
    destination_table_name: 'customer_address_entity_varchar',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'customer_eav_attribute',
    destination_table_name: 'customer_eav_attribute',
    primary_key: 'attribute_id',
  },
  {
    fields: [],
    table: 'customer_eav_attribute_website',
    destination_table_name: 'customer_eav_attribute_website',
    primary_key: 'attribute_id',
  },
  {
    fields: [],
    table: 'customer_entity',
    destination_table_name: 'customer_entity',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'customer_entity_datetime',
    destination_table_name: 'customer_entity_datetime',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'customer_entity_decimal',
    destination_table_name: 'customer_entity_decimal',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'customer_entity_int',
    destination_table_name: 'customer_entity_int',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'customer_entity_text',
    destination_table_name: 'customer_entity_text',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'customer_entity_varchar',
    destination_table_name: 'customer_entity_varchar',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'customer_form_attribute',
    destination_table_name: 'customer_form_attribute',
    primary_key: 'form_code',
  },
  {
    fields: [],
    table: 'customer_grid_flat',
    destination_table_name: 'customer_grid_flat',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'customer_group',
    destination_table_name: 'customer_group',
    primary_key: 'customer_group_id',
  },
  {
    fields: [],
    table: 'customer_log',
    destination_table_name: 'customer_log',
    primary_key: 'log_id',
  },
  {
    fields: [],
    table: 'customer_visitor',
    destination_table_name: 'customer_visitor',
    primary_key: 'visitor_id',
  },
  {
    fields: [],
    table: 'design_change',
    destination_table_name: 'design_change',
    primary_key: 'design_change_id',
  },
  {
    fields: [],
    table: 'design_config_grid_flat',
    destination_table_name: 'design_config_grid_flat',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'directory_country',
    destination_table_name: 'directory_country',
    primary_key: 'country_id',
  },
  {
    fields: [],
    table: 'directory_country_format',
    destination_table_name: 'directory_country_format',
    primary_key: 'country_format_id',
  },
  {
    fields: [],
    table: 'directory_country_region',
    destination_table_name: 'directory_country_region',
    primary_key: 'region_id',
  },
  {
    fields: [],
    table: 'directory_country_region_name',
    destination_table_name: 'directory_country_region_name',
    primary_key: 'locale',
  },
  {
    fields: [],
    table: 'directory_currency_rate',
    destination_table_name: 'directory_currency_rate',
    primary_key: 'currency_from',
  },
  {
    fields: [],
    table: 'downloadable_link',
    destination_table_name: 'downloadable_link',
    primary_key: 'link_id',
  },
  {
    fields: [],
    table: 'downloadable_link_price',
    destination_table_name: 'downloadable_link_price',
    primary_key: 'price_id',
  },
  {
    fields: [],
    table: 'downloadable_link_purchased',
    destination_table_name: 'downloadable_link_purchased',
    primary_key: 'purchased_id',
  },
  {
    fields: [],
    table: 'downloadable_link_purchased_item',
    destination_table_name: 'downloadable_link_purchased_item',
    primary_key: 'item_id',
  },
  {
    fields: [],
    table: 'downloadable_link_title',
    destination_table_name: 'downloadable_link_title',
    primary_key: 'title_id',
  },
  {
    fields: [],
    table: 'downloadable_sample',
    destination_table_name: 'downloadable_sample',
    primary_key: 'sample_id',
  },
  {
    fields: [],
    table: 'downloadable_sample_title',
    destination_table_name: 'downloadable_sample_title',
    primary_key: 'title_id',
  },
  {
    fields: [],
    table: 'eav_attribute',
    destination_table_name: 'eav_attribute',
    primary_key: 'attribute_id',
  },
  {
    fields: [],
    table: 'eav_attribute_group',
    destination_table_name: 'eav_attribute_group',
    primary_key: 'attribute_group_id',
  },
  {
    fields: [],
    table: 'eav_attribute_label',
    destination_table_name: 'eav_attribute_label',
    primary_key: 'attribute_label_id',
  },
  {
    fields: [],
    table: 'eav_attribute_option',
    destination_table_name: 'eav_attribute_option',
    primary_key: 'option_id',
  },
  {
    fields: [],
    table: 'eav_attribute_option_swatch',
    destination_table_name: 'eav_attribute_option_swatch',
    primary_key: 'swatch_id',
  },
  {
    fields: [],
    table: 'eav_attribute_option_value',
    destination_table_name: 'eav_attribute_option_value',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'eav_attribute_set',
    destination_table_name: 'eav_attribute_set',
    primary_key: 'attribute_set_id',
  },
  {
    fields: [],
    table: 'eav_entity',
    destination_table_name: 'eav_entity',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'eav_entity_attribute',
    destination_table_name: 'eav_entity_attribute',
    primary_key: 'entity_attribute_id',
  },
  {
    fields: [],
    table: 'eav_entity_datetime',
    destination_table_name: 'eav_entity_datetime',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'eav_entity_decimal',
    destination_table_name: 'eav_entity_decimal',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'eav_entity_int',
    destination_table_name: 'eav_entity_int',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'eav_entity_store',
    destination_table_name: 'eav_entity_store',
    primary_key: 'entity_store_id',
  },
  {
    fields: [],
    table: 'eav_entity_text',
    destination_table_name: 'eav_entity_text',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'eav_entity_type',
    destination_table_name: 'eav_entity_type',
    primary_key: 'entity_type_id',
  },
  {
    fields: [],
    table: 'eav_entity_varchar',
    destination_table_name: 'eav_entity_varchar',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'eav_form_element',
    destination_table_name: 'eav_form_element',
    primary_key: 'element_id',
  },
  {
    fields: [],
    table: 'eav_form_fieldset',
    destination_table_name: 'eav_form_fieldset',
    primary_key: 'fieldset_id',
  },
  {
    fields: [],
    table: 'eav_form_fieldset_label',
    destination_table_name: 'eav_form_fieldset_label',
    primary_key: 'fieldset_id',
  },
  {
    fields: [],
    table: 'eav_form_type',
    destination_table_name: 'eav_form_type',
    primary_key: 'type_id',
  },
  {
    fields: [],
    table: 'eav_form_type_entity',
    destination_table_name: 'eav_form_type_entity',
    primary_key: 'type_id',
  },
  {
    fields: [],
    table: 'email_template',
    destination_table_name: 'email_template',
    primary_key: 'template_id',
  },
  {
    fields: [],
    table: 'flag',
    destination_table_name: 'flag',
    primary_key: 'flag_id',
  },
  {
    fields: [],
    table: 'gift_message',
    destination_table_name: 'gift_message',
    primary_key: 'gift_message_id',
  },
  {
    fields: [],
    table: 'googleoptimizer_code',
    destination_table_name: 'googleoptimizer_code',
    primary_key: 'code_id',
  },
  {
    fields: [],
    table: 'import_history',
    destination_table_name: 'import_history',
    primary_key: 'history_id',
  },
  {
    fields: [],
    table: 'importexport_importdata',
    destination_table_name: 'importexport_importdata',
    primary_key: 'id',
  },
  {
    fields: [],
    table: 'indexer_state',
    destination_table_name: 'indexer_state',
    primary_key: 'state_id',
  },
  {
    fields: [],
    table: 'integration',
    destination_table_name: 'integration',
    primary_key: 'integration_id',
  },
  {
    fields: [],
    table: 'layout_link',
    destination_table_name: 'layout_link',
    primary_key: 'layout_link_id',
  },
  {
    fields: [],
    table: 'layout_update',
    destination_table_name: 'layout_update',
    primary_key: 'layout_update_id',
  },
  {
    fields: [],
    table: 'mview_state',
    destination_table_name: 'mview_state',
    primary_key: 'state_id',
  },
  {
    fields: [],
    table: 'newsletter_problem',
    destination_table_name: 'newsletter_problem',
    primary_key: 'problem_id',
  },
  {
    fields: [],
    table: 'newsletter_queue',
    destination_table_name: 'newsletter_queue',
    primary_key: 'queue_id',
  },
  {
    fields: [],
    table: 'newsletter_queue_link',
    destination_table_name: 'newsletter_queue_link',
    primary_key: 'queue_link_id',
  },
  {
    fields: [],
    table: 'newsletter_queue_store_link',
    destination_table_name: 'newsletter_queue_store_link',
    primary_key: 'queue_id',
  },
  {
    fields: [],
    table: 'newsletter_subscriber',
    destination_table_name: 'newsletter_subscriber',
    primary_key: 'subscriber_id',
  },
  {
    fields: [],
    table: 'newsletter_template',
    destination_table_name: 'newsletter_template',
    primary_key: 'template_id',
  },
  {
    fields: [],
    table: 'oauth_consumer',
    destination_table_name: 'oauth_consumer',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'oauth_nonce',
    destination_table_name: 'oauth_nonce',
    primary_key: 'nonce',
  },
  {
    fields: [],
    table: 'oauth_token',
    destination_table_name: 'oauth_token',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'oauth_token_request_log',
    destination_table_name: 'oauth_token_request_log',
    primary_key: 'log_id',
  },
  {
    fields: [],
    table: 'password_reset_request_event',
    destination_table_name: 'password_reset_request_event',
    primary_key: 'id',
  },
  {
    fields: [],
    table: 'paypal_billing_agreement',
    destination_table_name: 'paypal_billing_agreement',
    primary_key: 'agreement_id',
  },
  {
    fields: [],
    table: 'paypal_billing_agreement_order',
    destination_table_name: 'paypal_billing_agreement_order',
    primary_key: 'agreement_id',
  },
  {
    fields: [],
    table: 'paypal_cert',
    destination_table_name: 'paypal_cert',
    primary_key: 'cert_id',
  },
  {
    fields: [],
    table: 'paypal_payment_transaction',
    destination_table_name: 'paypal_payment_transaction',
    primary_key: 'transaction_id',
  },
  {
    fields: [],
    table: 'paypal_settlement_report',
    destination_table_name: 'paypal_settlement_report',
    primary_key: 'report_id',
  },
  {
    fields: [],
    table: 'paypal_settlement_report_row',
    destination_table_name: 'paypal_settlement_report_row',
    primary_key: 'row_id',
  },
  {
    fields: [],
    table: 'persistent_session',
    destination_table_name: 'persistent_session',
    primary_key: 'persistent_id',
  },
  {
    fields: [],
    table: 'product_alert_price',
    destination_table_name: 'product_alert_price',
    primary_key: 'alert_price_id',
  },
  {
    fields: [],
    table: 'product_alert_stock',
    destination_table_name: 'product_alert_stock',
    primary_key: 'alert_stock_id',
  },
  {
    fields: [],
    table: 'quote',
    destination_table_name: 'quote',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'quote_address',
    destination_table_name: 'quote_address',
    primary_key: 'address_id',
  },
  {
    fields: [],
    table: 'quote_address_item',
    destination_table_name: 'quote_address_item',
    primary_key: 'address_item_id',
  },
  {
    fields: [],
    table: 'quote_id_mask',
    destination_table_name: 'quote_id_mask',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'quote_item',
    destination_table_name: 'quote_item',
    primary_key: 'item_id',
  },
  {
    fields: [],
    table: 'quote_item_option',
    destination_table_name: 'quote_item_option',
    primary_key: 'option_id',
  },
  {
    fields: [],
    table: 'quote_payment',
    destination_table_name: 'quote_payment',
    primary_key: 'payment_id',
  },
  {
    fields: [],
    table: 'quote_shipping_rate',
    destination_table_name: 'quote_shipping_rate',
    primary_key: 'rate_id',
  },
  {
    fields: [],
    table: 'rating',
    destination_table_name: 'rating',
    primary_key: 'rating_id',
  },
  {
    fields: [],
    table: 'rating_entity',
    destination_table_name: 'rating_entity',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'rating_option',
    destination_table_name: 'rating_option',
    primary_key: 'option_id',
  },
  {
    fields: [],
    table: 'rating_option_vote',
    destination_table_name: 'rating_option_vote',
    primary_key: 'vote_id',
  },
  {
    fields: [],
    table: 'rating_option_vote_aggregated',
    destination_table_name: 'rating_option_vote_aggregated',
    primary_key: 'primary_id',
  },
  {
    fields: [],
    table: 'rating_store',
    destination_table_name: 'rating_store',
    primary_key: 'rating_id',
  },
  {
    fields: [],
    table: 'rating_title',
    destination_table_name: 'rating_title',
    primary_key: 'rating_id',
  },
  {
    fields: [],
    table: 'report_compared_product_index',
    destination_table_name: 'report_compared_product_index',
    primary_key: 'index_id',
  },
  {
    fields: [],
    table: 'report_event',
    destination_table_name: 'report_event',
    primary_key: 'event_id',
  },
  {
    fields: [],
    table: 'report_event_types',
    destination_table_name: 'report_event_types',
    primary_key: 'event_type_id',
  },
  {
    fields: [],
    table: 'report_viewed_product_aggregated_daily',
    destination_table_name: 'report_viewed_product_aggregated_daily',
    primary_key: 'id',
  },
  {
    fields: [],
    table: 'report_viewed_product_aggregated_monthly',
    destination_table_name: 'report_viewed_product_aggregated_monthly',
    primary_key: 'id',
  },
  {
    fields: [],
    table: 'report_viewed_product_aggregated_yearly',
    destination_table_name: 'report_viewed_product_aggregated_yearly',
    primary_key: 'id',
  },
  {
    fields: [],
    table: 'report_viewed_product_index',
    destination_table_name: 'report_viewed_product_index',
    primary_key: 'index_id',
  },
  {
    fields: [],
    table: 'reporting_counts',
    destination_table_name: 'reporting_counts',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'reporting_module_status',
    destination_table_name: 'reporting_module_status',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'reporting_orders',
    destination_table_name: 'reporting_orders',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'reporting_system_updates',
    destination_table_name: 'reporting_system_updates',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'reporting_users',
    destination_table_name: 'reporting_users',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'review',
    destination_table_name: 'review',
    primary_key: 'review_id',
  },
  {
    fields: [],
    table: 'review_detail',
    destination_table_name: 'review_detail',
    primary_key: 'detail_id',
  },
  {
    fields: [],
    table: 'review_entity',
    destination_table_name: 'review_entity',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'review_entity_summary',
    destination_table_name: 'review_entity_summary',
    primary_key: 'primary_id',
  },
  {
    fields: [],
    table: 'review_status',
    destination_table_name: 'review_status',
    primary_key: 'status_id',
  },
  {
    fields: [],
    table: 'review_store',
    destination_table_name: 'review_store',
    primary_key: 'review_id',
  },
  {
    fields: [],
    table: 'sales_bestsellers_aggregated_daily',
    destination_table_name: 'sales_bestsellers_aggregated_daily',
    primary_key: 'id',
  },
  {
    fields: [],
    table: 'sales_bestsellers_aggregated_monthly',
    destination_table_name: 'sales_bestsellers_aggregated_monthly',
    primary_key: 'id',
  },
  {
    fields: [],
    table: 'sales_bestsellers_aggregated_yearly',
    destination_table_name: 'sales_bestsellers_aggregated_yearly',
    primary_key: 'id',
  },
  {
    fields: [],
    table: 'sales_creditmemo',
    destination_table_name: 'sales_creditmemo',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'sales_creditmemo_comment',
    destination_table_name: 'sales_creditmemo_comment',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'sales_creditmemo_grid',
    destination_table_name: 'sales_creditmemo_grid',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'sales_creditmemo_item',
    destination_table_name: 'sales_creditmemo_item',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'sales_invoice',
    destination_table_name: 'sales_invoice',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'sales_invoice_comment',
    destination_table_name: 'sales_invoice_comment',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'sales_invoice_grid',
    destination_table_name: 'sales_invoice_grid',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'sales_invoice_item',
    destination_table_name: 'sales_invoice_item',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'sales_invoiced_aggregated',
    destination_table_name: 'sales_invoiced_aggregated',
    primary_key: 'id',
  },
  {
    fields: [],
    table: 'sales_invoiced_aggregated_order',
    destination_table_name: 'sales_invoiced_aggregated_order',
    primary_key: 'id',
  },
  {
    fields: [],
    table: 'sales_order',
    destination_table_name: 'sales_order',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'sales_order_address',
    destination_table_name: 'sales_order_address',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'sales_order_aggregated_created',
    destination_table_name: 'sales_order_aggregated_created',
    primary_key: 'id',
  },
  {
    fields: [],
    table: 'sales_order_aggregated_updated',
    destination_table_name: 'sales_order_aggregated_updated',
    primary_key: 'id',
  },
  {
    fields: [],
    table: 'sales_order_grid',
    destination_table_name: 'sales_order_grid',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'sales_order_item',
    destination_table_name: 'sales_order_item',
    primary_key: 'item_id',
  },
  {
    fields: [],
    table: 'sales_order_payment',
    destination_table_name: 'sales_order_payment',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'sales_order_status',
    destination_table_name: 'sales_order_status',
    primary_key: 'status',
  },
  {
    fields: [],
    table: 'sales_order_status_history',
    destination_table_name: 'sales_order_status_history',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'sales_order_status_label',
    destination_table_name: 'sales_order_status_label',
    primary_key: 'status',
  },
  {
    fields: [],
    table: 'sales_order_status_state',
    destination_table_name: 'sales_order_status_state',
    primary_key: 'status',
  },
  {
    fields: [],
    table: 'sales_order_tax',
    destination_table_name: 'sales_order_tax',
    primary_key: 'tax_id',
  },
  {
    fields: [],
    table: 'sales_order_tax_item',
    destination_table_name: 'sales_order_tax_item',
    primary_key: 'tax_item_id',
  },
  {
    fields: [],
    table: 'sales_payment_transaction',
    destination_table_name: 'sales_payment_transaction',
    primary_key: 'transaction_id',
  },
  {
    fields: [],
    table: 'sales_refunded_aggregated',
    destination_table_name: 'sales_refunded_aggregated',
    primary_key: 'id',
  },
  {
    fields: [],
    table: 'sales_refunded_aggregated_order',
    destination_table_name: 'sales_refunded_aggregated_order',
    primary_key: 'id',
  },
  {
    fields: [],
    table: 'sales_sequence_meta',
    destination_table_name: 'sales_sequence_meta',
    primary_key: 'meta_id',
  },
  {
    fields: [],
    table: 'sales_sequence_profile',
    destination_table_name: 'sales_sequence_profile',
    primary_key: 'profile_id',
  },
  {
    fields: [],
    table: 'sales_shipment',
    destination_table_name: 'sales_shipment',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'sales_shipment_comment',
    destination_table_name: 'sales_shipment_comment',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'sales_shipment_grid',
    destination_table_name: 'sales_shipment_grid',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'sales_shipment_item',
    destination_table_name: 'sales_shipment_item',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'sales_shipment_track',
    destination_table_name: 'sales_shipment_track',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'sales_shipping_aggregated',
    destination_table_name: 'sales_shipping_aggregated',
    primary_key: 'id',
  },
  {
    fields: [],
    table: 'sales_shipping_aggregated_order',
    destination_table_name: 'sales_shipping_aggregated_order',
    primary_key: 'id',
  },
  {
    fields: [],
    table: 'salesrule',
    destination_table_name: 'salesrule',
    primary_key: 'rule_id',
  },
  {
    fields: [],
    table: 'salesrule_coupon',
    destination_table_name: 'salesrule_coupon',
    primary_key: 'coupon_id',
  },
  {
    fields: [],
    table: 'salesrule_coupon_aggregated',
    destination_table_name: 'salesrule_coupon_aggregated',
    primary_key: 'id',
  },
  {
    fields: [],
    table: 'salesrule_coupon_aggregated_order',
    destination_table_name: 'salesrule_coupon_aggregated_order',
    primary_key: 'id',
  },
  {
    fields: [],
    table: 'salesrule_coupon_aggregated_updated',
    destination_table_name: 'salesrule_coupon_aggregated_updated',
    primary_key: 'id',
  },
  {
    fields: [],
    table: 'salesrule_coupon_usage',
    destination_table_name: 'salesrule_coupon_usage',
    primary_key: 'coupon_id',
  },
  {
    fields: [],
    table: 'salesrule_customer',
    destination_table_name: 'salesrule_customer',
    primary_key: 'rule_customer_id',
  },
  {
    fields: [],
    table: 'salesrule_customer_group',
    destination_table_name: 'salesrule_customer_group',
    primary_key: 'rule_id',
  },
  {
    fields: [],
    table: 'salesrule_label',
    destination_table_name: 'salesrule_label',
    primary_key: 'label_id',
  },
  {
    fields: [],
    table: 'salesrule_product_attribute',
    destination_table_name: 'salesrule_product_attribute',
    primary_key: 'rule_id',
  },
  {
    fields: [],
    table: 'salesrule_website',
    destination_table_name: 'salesrule_website',
    primary_key: 'rule_id',
  },
  {
    fields: [],
    table: 'search_query',
    destination_table_name: 'search_query',
    primary_key: 'query_id',
  },
  {
    fields: [],
    table: 'search_synonyms',
    destination_table_name: 'search_synonyms',
    primary_key: 'group_id',
  },
  {
    fields: [],
    table: 'sendfriend_log',
    destination_table_name: 'sendfriend_log',
    primary_key: 'log_id',
  },
  {
    fields: [],
    table: 'sequence_creditmemo_0',
    destination_table_name: 'sequence_creditmemo_0',
    primary_key: 'sequence_value',
  },
  {
    fields: [],
    table: 'sequence_creditmemo_1',
    destination_table_name: 'sequence_creditmemo_1',
    primary_key: 'sequence_value',
  },
  {
    fields: [],
    table: 'sequence_invoice_0',
    destination_table_name: 'sequence_invoice_0',
    primary_key: 'sequence_value',
  },
  {
    fields: [],
    table: 'sequence_invoice_1',
    destination_table_name: 'sequence_invoice_1',
    primary_key: 'sequence_value',
  },
  {
    fields: [],
    table: 'sequence_order_0',
    destination_table_name: 'sequence_order_0',
    primary_key: 'sequence_value',
  },
  {
    fields: [],
    table: 'sequence_order_1',
    destination_table_name: 'sequence_order_1',
    primary_key: 'sequence_value',
  },
  {
    fields: [],
    table: 'sequence_shipment_0',
    destination_table_name: 'sequence_shipment_0',
    primary_key: 'sequence_value',
  },
  {
    fields: [],
    table: 'sequence_shipment_1',
    destination_table_name: 'sequence_shipment_1',
    primary_key: 'sequence_value',
  },
  {
    fields: [],
    table: 'session',
    destination_table_name: 'session',
    primary_key: 'session_id',
  },
  {
    fields: [],
    table: 'setup_module',
    destination_table_name: 'setup_module',
    primary_key: 'module',
  },
  {
    fields: [],
    table: 'shipping_tablerate',
    destination_table_name: 'shipping_tablerate',
    primary_key: 'pk',
  },
  {
    fields: [],
    table: 'sitemap',
    destination_table_name: 'sitemap',
    primary_key: 'sitemap_id',
  },
  {
    fields: [],
    table: 'store',
    destination_table_name: 'store',
    primary_key: 'store_id',
  },
  {
    fields: [],
    table: 'store_group',
    destination_table_name: 'store_group',
    primary_key: 'group_id',
  },
  {
    fields: [],
    table: 'store_website',
    destination_table_name: 'store_website',
    primary_key: 'website_id',
  },
  {
    fields: [],
    table: 'tax_calculation',
    destination_table_name: 'tax_calculation',
    primary_key: 'tax_calculation_id',
  },
  {
    fields: [],
    table: 'tax_calculation_rate',
    destination_table_name: 'tax_calculation_rate',
    primary_key: 'tax_calculation_rate_id',
  },
  {
    fields: [],
    table: 'tax_calculation_rate_title',
    destination_table_name: 'tax_calculation_rate_title',
    primary_key: 'tax_calculation_rate_title_id',
  },
  {
    fields: [],
    table: 'tax_calculation_rule',
    destination_table_name: 'tax_calculation_rule',
    primary_key: 'tax_calculation_rule_id',
  },
  {
    fields: [],
    table: 'tax_class',
    destination_table_name: 'tax_class',
    primary_key: 'class_id',
  },
  {
    fields: [],
    table: 'tax_order_aggregated_created',
    destination_table_name: 'tax_order_aggregated_created',
    primary_key: 'id',
  },
  {
    fields: [],
    table: 'tax_order_aggregated_updated',
    destination_table_name: 'tax_order_aggregated_updated',
    primary_key: 'id',
  },
  {
    fields: [],
    table: 'theme',
    destination_table_name: 'theme',
    primary_key: 'theme_id',
  },
  {
    fields: [],
    table: 'theme_file',
    destination_table_name: 'theme_file',
    primary_key: 'theme_files_id',
  },
  {
    fields: [],
    table: 'translation',
    destination_table_name: 'translation',
    primary_key: 'key_id',
  },
  {
    fields: [],
    table: 'ui_bookmark',
    destination_table_name: 'ui_bookmark',
    primary_key: 'bookmark_id',
  },
  {
    fields: [],
    table: 'url_rewrite',
    destination_table_name: 'url_rewrite',
    primary_key: 'url_rewrite_id',
  },
  {
    fields: [],
    table: 'variable',
    destination_table_name: 'variable',
    primary_key: 'variable_id',
  },
  {
    fields: [],
    table: 'variable_value',
    destination_table_name: 'variable_value',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'vault_payment_token',
    destination_table_name: 'vault_payment_token',
    primary_key: 'entity_id',
  },
  {
    fields: [],
    table: 'vault_payment_token_order_payment_link',
    destination_table_name: 'vault_payment_token_order_payment_link',
    primary_key: 'order_payment_id',
  },
  {
    fields: [],
    table: 'weee_tax',
    destination_table_name: 'weee_tax',
    primary_key: 'value_id',
  },
  {
    fields: [],
    table: 'widget',
    destination_table_name: 'widget',
    primary_key: 'widget_id',
  },
  {
    fields: [],
    table: 'widget_instance',
    destination_table_name: 'widget_instance',
    primary_key: 'instance_id',
  },
  {
    fields: [],
    table: 'widget_instance_page',
    destination_table_name: 'widget_instance_page',
    primary_key: 'page_id',
  },
  {
    fields: [],
    table: 'widget_instance_page_layout',
    destination_table_name: 'widget_instance_page_layout',
    primary_key: 'page_id',
  },
  {
    fields: [],
    table: 'wishlist',
    destination_table_name: 'wishlist',
    primary_key: 'wishlist_id',
  },
  {
    fields: [],
    table: 'wishlist_item',
    destination_table_name: 'wishlist_item',
    primary_key: 'wishlist_item_id',
  },
  {
    fields: [],
    table: 'wishlist_item_option',
    destination_table_name: 'wishlist_item_option',
    primary_key: 'option_id',
  },
];
module.exports = magentoSchema;
